apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-simple-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host:   # ممكن تبدأي من غير host وتسيبيه فاضي
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-simple-nginx
            port:
              number: 80